# Site settings
title: MVS Solution
email: nirajftw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mvssolution.com" # the base hostname & protocol for your site

twitter_username: nirajftw
github_username: nirajftw

# Build settings
markdown: kramdown
